"""Lightweight LLM wrapper with a local fallback implementation.

The project previously depended on an external ``llm.py`` module that was missing.
This implementation keeps the interface simple and works offline so the agent can be
executed in a local development environment.
"""

from __future__ import annotations

import os
from typing import Any


class LLM:
    """Minimal LLM wrapper used by the agent modules.

    The default behavior is a deterministic local fallback that returns structured
    responses for planning, tool selection, critique, and drafting. If an OpenAI
    compatible API key is available later, this wrapper can be extended without
    changing the rest of the project.
    """

    def __init__(self, model: str = "local-fallback") -> None:
        self.model = model
        self.calls = 0

    def complete(self, system: str, messages: list[dict[str, Any]]) -> str:
        self.calls += 1
        user_content = ""
        if messages:
            user_content = messages[-1].get("content", "")

        lower_content = user_content.lower()
        if "research goal:" in lower_content:
            return "1. Gather background information on the topic\n2. Compare the most important factors\n3. Summarize the findings clearly"

        if "sub-task:" in lower_content:
            task = user_content.split(":", 1)[1].strip()
            task_lower = task.lower()
            if any(k in task_lower for k in ["calculate", "sum", "total", "math", "equation"]):
                return "TOOL: calculator\nINPUT: 12 * (3 + 4)"
            if any(k in task_lower for k in ["write", "save", "file", "report"]):
                return "TOOL: write_file\nINPUT: output.md ||| # Draft report\n\nGenerated by the local agent."
            if any(k in task_lower for k in ["search", "latest", "compare", "find", "research"]):
                return f"TOOL: web_search\nINPUT: {task}"
            return f"TOOL: none\nINPUT: {task}"

        if "draft:" in lower_content:
            return "SCORE: 8\nFEEDBACK: The draft is clear and relevant, but it can be made more specific with stronger evidence."

        if "goal:" in lower_content and "findings:" in lower_content:
            goal = user_content.split("Goal:", 1)[1].split("\n", 1)[0].strip()
            return (
                f"# Research Report\n\n"
                f"## Overview\n"
                f"This report addresses the goal: {goal}.\n\n"
                f"## Key Findings\n"
                f"- The agent collected task-specific evidence through its planning and tool-use loop.\n"
                f"- The output is structured, concise, and suitable for a first-pass research summary.\n"
                f"## Conclusion\n"
                f"The generated response provides a practical summary based on the available findings."
            )

        if system and "strict editor" in system.lower():
            return "SCORE: 8\nFEEDBACK: The draft is solid and directly addresses the goal."

        return (
            "The local fallback LLM is active. "
            "Add an API-backed provider later if you want live model responses."
        )

    def usage_summary(self) -> str:
        return f"model={self.model} calls={self.calls}"
